project_id = "yhuoexfivagwuaudjqan"

[functions.extract-document-data]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.daily-checks]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.google-oauth-refresh]
verify_jwt = false
