/**
 * src/config/permissions.ts
 *
 * Role-based permissions configuration for GlobalWorker platform.
 * This file defines what each user role can and cannot do in the system.
 */

export type InternalRole = 'admin' | 'recruiter' | 'operations_manager' | 'documentation_staff' | 'documentation_lead' | 'sales_manager' | 'project_manager';

export type AgencyRole = 'agency_owner' | 'agency_recruiter' | 'agency_document_staff' | 'agency_viewer';

export type EmployerRole = 'employer_admin' | 'employer_hr' | 'employer_hiring_manager' | 'employer_viewer';

export type AllRoles = InternalRole | AgencyRole | EmployerRole;

// ─── Permission Categories ────────────────────────────────────────────────────

export interface RolePermissions {
  // User Management
  createUsers: boolean;
  viewAllUsers: boolean;
  modifyUserRoles: boolean;

  // Candidates
  viewAllCandidates: boolean;
  createCandidates: boolean;
  editCandidates: boolean;
  deleteCandidates: boolean;
  exportCandidates: boolean;

  // Jobs
  viewAllJobs: boolean;
  createJobs: boolean;
  editJobs: boolean;
  deleteJobs: boolean;
  linkCandidatesToJobs: boolean;

  // Projects
  viewAllProjects: boolean;
  createProjects: boolean;
  editProjects: boolean;
  deleteProjects: boolean;

  // Documents
  viewAllDocuments: boolean;
  uploadDocuments: boolean;
  deleteDocuments: boolean;

  // Workflow Management
  viewAllWorkflows: boolean;
  createWorkflows: boolean;
  advanceWorkflowPhases: boolean;
  reviewApproveDocuments: boolean;

  // Agencies
  viewAllAgencies: boolean;
  approveRejectAgencies: boolean;
  viewAgencyProfiles: boolean;
  editAgencyDetails: boolean;
  viewAgencyWorkers: boolean;

  // Team Management (for agencies)
  inviteTeamMembers: boolean;
  removeTeamMembers: boolean;
  changeTeamMemberRoles: boolean;
  viewTeamActivityLog: boolean;

  // Notes & Activity
  viewAllNotes: boolean;
  createNotes: boolean;
  editOwnNotes: boolean;
  deleteAnyNotes: boolean;

  // System
  accessAdminPanel: boolean;
  viewSystemLogs: boolean;
  modifySettings: boolean;
  createRegistrationCodes: boolean;

  // Billing
  viewBilling: boolean;
  manageBilling: boolean;
  viewInvoices: boolean;
  managePaymentMethods: boolean;

  // Employer-specific permissions
  inviteEmployerTeam: boolean;
  removeEmployerTeam: boolean;
  manageEmployerTeam: boolean;
  viewCompanyProfile: boolean;
  editCompanyProfile: boolean;
  uploadCompanyDocuments: boolean;
  viewAssignedProjects: boolean;
  viewAllCompanyProjects: boolean;
  viewProjectCandidates: boolean;
  exportCandidateLists: boolean;
  viewCandidateDocuments: boolean;
  scheduleInterviews: boolean;
  viewInterviews: boolean;
  provideFeedback: boolean;
  createOffers: boolean;
  viewOffers: boolean;
  approveOffers: boolean;
}

// ─── Internal Staff Permissions ───────────────────────────────────────────────

const ADMIN_PERMISSIONS: RolePermissions = {
  createUsers: true,
  viewAllUsers: true,
  modifyUserRoles: true,
  viewAllCandidates: true,
  createCandidates: true,
  editCandidates: true,
  deleteCandidates: true,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: true,
  editJobs: true,
  deleteJobs: true,
  linkCandidatesToJobs: true,
  viewAllProjects: true,
  createProjects: true,
  editProjects: true,
  deleteProjects: true,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: true,
  viewAllWorkflows: true,
  createWorkflows: true,
  advanceWorkflowPhases: true,
  reviewApproveDocuments: true,
  viewAllAgencies: true,
  approveRejectAgencies: true,
  viewAgencyProfiles: true,
  editAgencyDetails: true,
  viewAgencyWorkers: true,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: true,
  accessAdminPanel: true,
  viewSystemLogs: true,
  modifySettings: true,
  createRegistrationCodes: true,
  viewBilling: true,
  manageBilling: true,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const RECRUITER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: true,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: true,
  editCandidates: true,
  deleteCandidates: false,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: true,
  editJobs: true,
  deleteJobs: false,
  linkCandidatesToJobs: true,
  viewAllProjects: true,
  createProjects: true,
  editProjects: true,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: false,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: true,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: true,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const OPERATIONS_MANAGER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: true,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: true,
  editCandidates: true,
  deleteCandidates: false,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: true,
  editJobs: true,
  deleteJobs: false,
  linkCandidatesToJobs: true,
  viewAllProjects: true,
  createProjects: true,
  editProjects: true,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: true,
  viewAllWorkflows: true,
  createWorkflows: true,
  advanceWorkflowPhases: true,
  reviewApproveDocuments: true,
  viewAllAgencies: true,
  approveRejectAgencies: true,
  viewAgencyProfiles: true,
  editAgencyDetails: true,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: true,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const DOCUMENTATION_STAFF_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: true,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: true,
  viewAllWorkflows: true,
  createWorkflows: true,
  advanceWorkflowPhases: true,
  reviewApproveDocuments: true,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

// ─── Agency Team Permissions ──────────────────────────────────────────────────

const AGENCY_OWNER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: true,
  editCandidates: true,
  deleteCandidates: true,
  exportCandidates: true,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: true,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: true,
  viewAgencyWorkers: false,
  inviteTeamMembers: true,
  removeTeamMembers: true,
  changeTeamMemberRoles: true,
  viewTeamActivityLog: true,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: true,
  manageBilling: true,
  viewInvoices: true,
  managePaymentMethods: true,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const AGENCY_RECRUITER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: true,
  editCandidates: true,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: false,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const AGENCY_DOCUMENT_STAFF_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: false,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

const AGENCY_VIEWER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: false,
  editOwnNotes: false,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

// ─── Documentation Lead Permissions ───────────────────────────────────────────

const DOCUMENTATION_LEAD_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: true,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: true,
  deleteDocuments: true,
  viewAllWorkflows: true,
  createWorkflows: true,
  advanceWorkflowPhases: true,
  reviewApproveDocuments: true,
  viewAllAgencies: true,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: true,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: true,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

// ─── Sales Manager Permissions ────────────────────────────────────────────────

const SALES_MANAGER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: true,
  modifyUserRoles: false,
  viewAllCandidates: true,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: true,
  viewAllJobs: true,
  createJobs: true,
  editJobs: true,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: true,
  editProjects: true,
  deleteProjects: false,
  viewAllDocuments: true,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: true,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: true,
  approveRejectAgencies: false,
  viewAgencyProfiles: true,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: true,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: true,
  manageBilling: false,
  viewInvoices: true,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

// ─── Project Manager Permissions ──────────────────────────────────────────────
// Project Managers only see Dashboard and Projects assigned to them.

const PROJECT_MANAGER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: false,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: true,
  createProjects: false,
  editProjects: true,
  deleteProjects: false,
  viewAllDocuments: false,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: false,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: false,
  createNotes: false,
  editOwnNotes: false,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: false,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: false,
  viewAllCompanyProjects: false,
  viewProjectCandidates: false,
  exportCandidateLists: false,
  viewCandidateDocuments: false,
  scheduleInterviews: false,
  viewInterviews: false,
  provideFeedback: false,
  createOffers: false,
  viewOffers: false,
  approveOffers: false,
};

// ─── Employer Team Permissions ────────────────────────────────────────────────

const EMPLOYER_ADMIN_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: false,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: false,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: false,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: false,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: true,
  managePaymentMethods: true,
  inviteEmployerTeam: true,
  removeEmployerTeam: true,
  manageEmployerTeam: true,
  viewCompanyProfile: true,
  editCompanyProfile: true,
  uploadCompanyDocuments: true,
  viewAssignedProjects: false,
  viewAllCompanyProjects: true,
  viewProjectCandidates: true,
  exportCandidateLists: true,
  viewCandidateDocuments: true,
  scheduleInterviews: true,
  viewInterviews: true,
  provideFeedback: true,
  createOffers: true,
  viewOffers: true,
  approveOffers: true,
};

const EMPLOYER_HR_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: false,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: false,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: false,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: false,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: true,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: true,
  viewAllCompanyProjects: false,
  viewProjectCandidates: true,
  exportCandidateLists: true,
  viewCandidateDocuments: true,
  scheduleInterviews: true,
  viewInterviews: true,
  provideFeedback: true,
  createOffers: false,
  viewOffers: true,
  approveOffers: false,
};

const EMPLOYER_HIRING_MANAGER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: false,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: false,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: false,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: false,
  createNotes: true,
  editOwnNotes: true,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: true,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: true,
  viewAllCompanyProjects: false,
  viewProjectCandidates: true,
  exportCandidateLists: false,
  viewCandidateDocuments: true,
  scheduleInterviews: true,
  viewInterviews: true,
  provideFeedback: true,
  createOffers: false,
  viewOffers: true,
  approveOffers: false,
};

const EMPLOYER_VIEWER_PERMISSIONS: RolePermissions = {
  createUsers: false,
  viewAllUsers: false,
  modifyUserRoles: false,
  viewAllCandidates: false,
  createCandidates: false,
  editCandidates: false,
  deleteCandidates: false,
  exportCandidates: false,
  viewAllJobs: false,
  createJobs: false,
  editJobs: false,
  deleteJobs: false,
  linkCandidatesToJobs: false,
  viewAllProjects: false,
  createProjects: false,
  editProjects: false,
  deleteProjects: false,
  viewAllDocuments: false,
  uploadDocuments: false,
  deleteDocuments: false,
  viewAllWorkflows: false,
  createWorkflows: false,
  advanceWorkflowPhases: false,
  reviewApproveDocuments: false,
  viewAllAgencies: false,
  approveRejectAgencies: false,
  viewAgencyProfiles: false,
  editAgencyDetails: false,
  viewAgencyWorkers: false,
  inviteTeamMembers: false,
  removeTeamMembers: false,
  changeTeamMemberRoles: false,
  viewTeamActivityLog: false,
  viewAllNotes: false,
  createNotes: false,
  editOwnNotes: false,
  deleteAnyNotes: false,
  accessAdminPanel: false,
  viewSystemLogs: false,
  modifySettings: false,
  createRegistrationCodes: false,
  viewBilling: false,
  manageBilling: false,
  viewInvoices: false,
  managePaymentMethods: false,
  inviteEmployerTeam: false,
  removeEmployerTeam: false,
  manageEmployerTeam: false,
  viewCompanyProfile: true,
  editCompanyProfile: false,
  uploadCompanyDocuments: false,
  viewAssignedProjects: true,
  viewAllCompanyProjects: false,
  viewProjectCandidates: true,
  exportCandidateLists: false,
  viewCandidateDocuments: true,
  scheduleInterviews: false,
  viewInterviews: true,
  provideFeedback: false,
  createOffers: false,
  viewOffers: true,
  approveOffers: false,
};


// ─── Permissions Map ──────────────────────────────────────────────────────────

export const PERMISSIONS_BY_ROLE: Record<AllRoles, RolePermissions> = {
  admin: ADMIN_PERMISSIONS,
  recruiter: RECRUITER_PERMISSIONS,
  operations_manager: OPERATIONS_MANAGER_PERMISSIONS,
  documentation_staff: DOCUMENTATION_STAFF_PERMISSIONS,
  documentation_lead: DOCUMENTATION_LEAD_PERMISSIONS,
  sales_manager: SALES_MANAGER_PERMISSIONS,
  project_manager: PROJECT_MANAGER_PERMISSIONS,
  agency_owner: AGENCY_OWNER_PERMISSIONS,
  agency_recruiter: AGENCY_RECRUITER_PERMISSIONS,
  agency_document_staff: AGENCY_DOCUMENT_STAFF_PERMISSIONS,
  agency_viewer: AGENCY_VIEWER_PERMISSIONS,
  employer_admin: EMPLOYER_ADMIN_PERMISSIONS,
  employer_hr: EMPLOYER_HR_PERMISSIONS,
  employer_hiring_manager: EMPLOYER_HIRING_MANAGER_PERMISSIONS,
  employer_viewer: EMPLOYER_VIEWER_PERMISSIONS,
};

// ─── Helper Functions ─────────────────────────────────────────────────────────

/**
 * Get permissions for a specific role
 */
export function getPermissions(role: AllRoles): RolePermissions {
  return PERMISSIONS_BY_ROLE[role];
}

/**
 * Check if a role has a specific permission
 */
export function hasPermission(
  role: AllRoles,
  permission: keyof RolePermissions
): boolean {
  return PERMISSIONS_BY_ROLE[role][permission];
}

/**
 * Check if any of multiple roles has a specific permission
 */
export function hasAnyPermission(
  roles: AllRoles[],
  permission: keyof RolePermissions
): boolean {
  return roles.some((role) => hasPermission(role, permission));
}

/**
 * Get human-readable role name
 */
export function getRoleName(role: AllRoles): string {
  const names: Record<AllRoles, string> = {
    admin: 'Administrator',
    recruiter: 'Recruiter',
    operations_manager: 'Operations Manager',
    documentation_staff: 'Documentation Staff',
    documentation_lead: 'Documentation Lead',
    sales_manager: 'Sales Manager',
    project_manager: 'Project Manager',
    agency_owner: 'Agency Owner',
    agency_recruiter: 'Agency Recruiter',
    agency_document_staff: 'Agency Document Staff',
    agency_viewer: 'Agency Viewer',
    employer_admin: 'Employer Admin',
    employer_hr: 'Employer HR',
    employer_hiring_manager: 'Employer Hiring Manager',
    employer_viewer: 'Employer Viewer',
  };
  return names[role];
}

/**
 * Check if role is internal staff
 */
export function isInternalStaff(role: AllRoles): boolean {
  return ['admin', 'recruiter', 'operations_manager', 'documentation_staff', 'documentation_lead', 'sales_manager', 'project_manager'].includes(role);
}

/**
 * Check if role is agency team member
 */
export function isAgencyTeam(role: AllRoles): boolean {
  return ['agency_owner', 'agency_recruiter', 'agency_document_staff', 'agency_viewer'].includes(role);
}

/**
 * Check if role is employer team member
 */
export function isEmployerTeam(role: AllRoles): boolean {
  return ['employer_admin', 'employer_hr', 'employer_hiring_manager', 'employer_viewer'].includes(role);
}
