
-- Table to store editable role permissions as JSONB per role
CREATE TABLE public.role_permissions (
  role TEXT PRIMARY KEY,
  permissions JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id)
);

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read permissions
CREATE POLICY "Authenticated users can view role permissions"
ON public.role_permissions
FOR SELECT
USING (is_authenticated());

-- Only admins can modify
CREATE POLICY "Admins can update role permissions"
ON public.role_permissions
FOR UPDATE
USING (has_role(auth.uid(), 'admin'))
WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can insert role permissions"
ON public.role_permissions
FOR INSERT
WITH CHECK (has_role(auth.uid(), 'admin'));

-- Seed with default permissions for all 8 roles
INSERT INTO public.role_permissions (role, permissions) VALUES
('admin', '{"createUsers":true,"viewAllUsers":true,"modifyUserRoles":true,"viewAllCandidates":true,"createCandidates":true,"editCandidates":true,"deleteCandidates":true,"exportCandidates":true,"viewAllJobs":true,"createJobs":true,"editJobs":true,"deleteJobs":true,"linkCandidatesToJobs":true,"viewAllProjects":true,"createProjects":true,"editProjects":true,"deleteProjects":true,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":true,"viewAllWorkflows":true,"createWorkflows":true,"advanceWorkflowPhases":true,"reviewApproveDocuments":true,"viewAllAgencies":true,"approveRejectAgencies":true,"viewAgencyProfiles":true,"editAgencyDetails":true,"viewAgencyWorkers":true,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":true,"accessAdminPanel":true,"viewSystemLogs":true,"modifySettings":true,"createRegistrationCodes":true,"viewBilling":true,"manageBilling":true,"viewInvoices":false,"managePaymentMethods":false}'),
('recruiter', '{"createUsers":false,"viewAllUsers":true,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":true,"editCandidates":true,"deleteCandidates":false,"exportCandidates":true,"viewAllJobs":true,"createJobs":true,"editJobs":true,"deleteJobs":false,"linkCandidatesToJobs":true,"viewAllProjects":true,"createProjects":true,"editProjects":true,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":false,"viewAllWorkflows":true,"createWorkflows":false,"advanceWorkflowPhases":false,"reviewApproveDocuments":false,"viewAllAgencies":true,"approveRejectAgencies":false,"viewAgencyProfiles":true,"editAgencyDetails":false,"viewAgencyWorkers":true,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}'),
('operations_manager', '{"createUsers":false,"viewAllUsers":true,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":true,"editCandidates":true,"deleteCandidates":false,"exportCandidates":true,"viewAllJobs":true,"createJobs":true,"editJobs":true,"deleteJobs":false,"linkCandidatesToJobs":true,"viewAllProjects":true,"createProjects":true,"editProjects":true,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":true,"viewAllWorkflows":true,"createWorkflows":true,"advanceWorkflowPhases":true,"reviewApproveDocuments":true,"viewAllAgencies":true,"approveRejectAgencies":true,"viewAgencyProfiles":true,"editAgencyDetails":true,"viewAgencyWorkers":false,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":true,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}'),
('documentation_staff', '{"createUsers":false,"viewAllUsers":true,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":false,"editCandidates":false,"deleteCandidates":false,"exportCandidates":true,"viewAllJobs":true,"createJobs":false,"editJobs":false,"deleteJobs":false,"linkCandidatesToJobs":false,"viewAllProjects":true,"createProjects":false,"editProjects":false,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":true,"viewAllWorkflows":true,"createWorkflows":true,"advanceWorkflowPhases":true,"reviewApproveDocuments":true,"viewAllAgencies":false,"approveRejectAgencies":false,"viewAgencyProfiles":false,"editAgencyDetails":false,"viewAgencyWorkers":false,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}'),
('agency_owner', '{"createUsers":false,"viewAllUsers":false,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":true,"editCandidates":true,"deleteCandidates":true,"exportCandidates":true,"viewAllJobs":false,"createJobs":false,"editJobs":false,"deleteJobs":false,"linkCandidatesToJobs":false,"viewAllProjects":false,"createProjects":false,"editProjects":false,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":true,"viewAllWorkflows":true,"createWorkflows":false,"advanceWorkflowPhases":false,"reviewApproveDocuments":false,"viewAllAgencies":false,"approveRejectAgencies":false,"viewAgencyProfiles":true,"editAgencyDetails":true,"viewAgencyWorkers":false,"inviteTeamMembers":true,"removeTeamMembers":true,"changeTeamMemberRoles":true,"viewTeamActivityLog":true,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":true,"manageBilling":true,"viewInvoices":true,"managePaymentMethods":true}'),
('agency_recruiter', '{"createUsers":false,"viewAllUsers":false,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":true,"editCandidates":true,"deleteCandidates":false,"exportCandidates":false,"viewAllJobs":false,"createJobs":false,"editJobs":false,"deleteJobs":false,"linkCandidatesToJobs":false,"viewAllProjects":false,"createProjects":false,"editProjects":false,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":false,"viewAllWorkflows":true,"createWorkflows":false,"advanceWorkflowPhases":false,"reviewApproveDocuments":false,"viewAllAgencies":false,"approveRejectAgencies":false,"viewAgencyProfiles":true,"editAgencyDetails":false,"viewAgencyWorkers":false,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}'),
('agency_document_staff', '{"createUsers":false,"viewAllUsers":false,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":false,"editCandidates":false,"deleteCandidates":false,"exportCandidates":false,"viewAllJobs":false,"createJobs":false,"editJobs":false,"deleteJobs":false,"linkCandidatesToJobs":false,"viewAllProjects":false,"createProjects":false,"editProjects":false,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":true,"deleteDocuments":false,"viewAllWorkflows":true,"createWorkflows":false,"advanceWorkflowPhases":false,"reviewApproveDocuments":false,"viewAllAgencies":false,"approveRejectAgencies":false,"viewAgencyProfiles":true,"editAgencyDetails":false,"viewAgencyWorkers":false,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":true,"editOwnNotes":true,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}'),
('agency_viewer', '{"createUsers":false,"viewAllUsers":false,"modifyUserRoles":false,"viewAllCandidates":true,"createCandidates":false,"editCandidates":false,"deleteCandidates":false,"exportCandidates":false,"viewAllJobs":false,"createJobs":false,"editJobs":false,"deleteJobs":false,"linkCandidatesToJobs":false,"viewAllProjects":false,"createProjects":false,"editProjects":false,"deleteProjects":false,"viewAllDocuments":true,"uploadDocuments":false,"deleteDocuments":false,"viewAllWorkflows":true,"createWorkflows":false,"advanceWorkflowPhases":false,"reviewApproveDocuments":false,"viewAllAgencies":false,"approveRejectAgencies":false,"viewAgencyProfiles":true,"editAgencyDetails":false,"viewAgencyWorkers":false,"inviteTeamMembers":false,"removeTeamMembers":false,"changeTeamMemberRoles":false,"viewTeamActivityLog":false,"viewAllNotes":true,"createNotes":false,"editOwnNotes":false,"deleteAnyNotes":false,"accessAdminPanel":false,"viewSystemLogs":false,"modifySettings":false,"createRegistrationCodes":false,"viewBilling":false,"manageBilling":false,"viewInvoices":false,"managePaymentMethods":false}');
